### ISSUE TITLE
Bump GWT version to 2.8-rc2

### ISSUE THREAD

**Issue by davido** [ekuefler/bazel-gwt#1]
It turns out that GWT team unboundled most of it dependencies from `gwt-dev.jar`. See my attempt to upgrade GWT in Gerrit Code Review project: [1]. It also upgraded `asm` to 3.1.

[1] https://gerrit-review.googlesource.com/#/c/67921/14/lib/gwt/BUCK@30
[2] https://gerrit-review.googlesource.com/#/c/83771

**Comment by ekuefler** [comment]
I've done this in the official repo at https://github.com/bazelbuild/rules_gwt, which is now available. Give it a try! This repo will be retired soon.
